apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: coraza-waf-all
  namespace: default
spec:
  url: oci://ghcr.io/corazawaf/coraza-proxy-wasm:latest
  imagePullPolicy: IfNotPresent
  phase: AUTHN
  pluginConfig:
    rules: |
      Include @recommended-conf
      SecRuleEngine DetectionOnly
      Include @crs-setup-conf
      Include @owasp_crs/*.conf