apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: disable-front-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: front
  mtls:
    mode: DISABLE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: disable-cpu-bench-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: cpu-bench
  mtls:
    mode: DISABLE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: disable-mem-bench-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: mem-bench
  mtls:
    mode: DISABLE
