apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: enable-front-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: front
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: enable-cpu-bench-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: cpu-bench
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: enable-mem-bench-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: mem-bench
  mtls:
    mode: STRICT
