apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-bench
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-bench
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1              
  selector:
    matchLabels:
      app: cpu-bench
      version: v1
  template:
    metadata:
      labels:
        app: cpu-bench
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: cpu-bench
          image: localhost:5000/cpu-bench
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
      terminationGracePeriodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-bench-service
  labels:
    app: cpu-bench
    service: cpu-bench
spec:
  selector:
    app: cpu-bench
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-cpu
