apiVersion: v1
kind: ServiceAccount
metadata:
  name: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1        
      maxSurge: 1              
  selector:
    matchLabels:
      app: front
      version: v1
  template:
    metadata:
      labels:
        app: front
        version: v1
    spec:
      serviceAccountName: front
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: front
          image: localhost:5000/front
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:                
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      terminationGracePeriodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front
    service: front
spec:
  selector:
    app: front
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-front