---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1        
      maxSurge: 1              
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: echo-server
          image: localhost:5000/front
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:                
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      terminationGracePeriodSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-bench
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1              
  selector:
    matchLabels:
      app: cpu-bench
  template:
    metadata:
      labels:
        app: cpu-bench
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: echo-server
          image: localhost:5000/cpu-bench
          ports:
            - name: http
              containerPort: 3000
      terminationGracePeriodSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-bench
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1        
      maxSurge: 1              
  selector:
    matchLabels:
      app: mem-bench
  template:
    metadata:
      labels:
        app: mem-bench
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: echo-server
          image: localhost:5000/mem-bench
          ports:
            - name: http
              containerPort: 3000
      terminationGracePeriodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1500
      targetPort: 3000
      name: tcp-front
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-bench-service
spec:
  selector:
    app: cpu-bench
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1500
      targetPort: 3000
      name: tcp-cpu
---
apiVersion: v1
kind: Service
metadata:
  name: mem-bench-service
spec:
  selector:
    app: mem-bench
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1500
      targetPort: 3000
      name: tcp-mem

